[project]
name = "testagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp>=1.25.0",
    "openai>=2.14.0",
    "yt-dlp>=2025.12.8",
]
